### PR TITLE
Upgrade to koa router 5.1.2

### PR DESCRIPTION
**Pull request by ajacksified**
:eyeglasses: @curioussavage and maybe @dwick

### CODE REVIEW

**Comment by curioussavage** [comment]
:fish:

**Comment by dwick** [comment]
:running:

**Comment by ajacksified** [comment]
Blocked by https://github.com/alexmingoia/koa-router/pull/152

**Comment by dwick** [comment]
@ajacksified that blocker was fixed, is this still relevant or can it be closed?

**Comment by curioussavage** [comment]
🏃  to clean up my salon

**Comment by dwick** [comment]
:running:

**Comment by dwick** [comment]
🏃

**Comment by dwick** [comment]
:runner:

**Comment by dwick** [comment]
@curioussavage did you get it to work?

**Comment by ajacksified** [comment]
@dwick horse is dead, long live ~chariot~ ~mothership~ platform

**Comment by dwick** [comment]
it's won't get out of my salon!

**Comment by ajacksified** [comment]
:nail_care:

**Comment by ajacksified** [comment]
:troll:

**Comment by curioussavage** [comment]
rip 🐴  

good times though..

**Comment by curioussavage** [comment]
@dwick don't see it in harold anymore.

**Pull request closed without merging**
